name: Flight Deal Finder

env:
    SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
    SENDER_EMAIL_PASS: ${{secrets.SENDER_EMAIL_PASSWORD}}
    SERP_API_KEY: ${{secrets.SERP_API_KEY}}
    SHEETS_URL_FLIGHT_DEAL: ${{secrets.SHEETS_URL_FLIGHT_DEAL}}

on:
  
  # The Cron Schedule
  schedule:
    - cron: "* * * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  

  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python 'Day 39 - Flight Deal Finder/main.py'
